Repository codex-team/editor.js, pull requests merged in 2020-04, with the labels that each got.

#1106 [Feature] i18n
  dist/editor.js
  dist/editor.js.LICENSE
  docs/CHANGELOG.md
  docs/api.md
  example/example-dev.html
  example/example-i18n.html
  src/components/block-tunes/block-tune-delete.ts
  src/components/block-tunes/block-tune-move-down.ts
  src/components/block-tunes/block-tune-move-up.ts
  src/components/block.ts
  src/components/core.ts
  src/components/i18n/index.ts
  src/components/i18n/locales/en/messages.json
  src/components/i18n/namespace-internal.ts
  src/components/inline-tools/inline-tool-link.ts
  src/components/modules/api/i18n.ts
  src/components/modules/api/index.ts
  src/components/modules/blockManager.ts
  src/components/modules/paste.ts
  src/components/modules/toolbar/conversion.ts
  src/components/modules/toolbar/index.ts
  src/components/modules/toolbar/inline.ts
  src/components/modules/toolbar/toolbox.ts
  src/components/modules/tools.ts
  src/components/tools/stub/index.ts
  src/types-internal/editor-modules.d.ts
  src/types-internal/i18n-internal-namespace.d.ts
  tsconfig.json
  types/api/i18n.d.ts
  types/api/index.d.ts
  types/configs/editor-config.d.ts
  types/configs/i18n-config.d.ts
  types/configs/i18n-dictionary.d.ts
  types/configs/index.d.ts
  types/index.d.ts
Labels: feature

#1096 fix $.isEmpty performance
  dist/editor.js
  docs/CHANGELOG.md
  src/components/dom.ts
Labels: approved

#1108 Allowing deleting block by block id
  dist/editor.js
  docs/CHANGELOG.md
  src/components/modules/api/blocks.ts
  types/api/blocks.d.ts
Labels: approved, conflicts
