Repository codex-team/editor.js, pull requests merged in 2020-08, with the labels that each got.

#1201 <fix> toolbar--opened overlap with certain text [issue 1196]
  dist/editor.js
  docs/CHANGELOG.md
  src/components/utils.ts
Labels: viewed

#1264 Tools destroy called when the editor is destroyed
  dist/editor.js
  docs/CHANGELOG.md
  docs/tools.md
  src/components/modules/blockManager.ts
  src/components/modules/tools.ts
  types/tools/block-tool.d.ts
  types/tools/tool.d.ts
Labels: discussion

#1214 Fix for input and textarea bug
  dist/editor.js
  docs/CHANGELOG.md
  src/components/block/index.ts
  src/components/modules/caret.ts
Labels: bug
